apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketweb
  namespace: rocket
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: rocketweb
    spec:
      containers:
      - image: jannemattila/rocket:latest
        name: rocketweb
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: APPLICATION_INSIGHTS_IKEY
            value: ""